version: '3'

services:
  nginx-demo:
    image: nginx
    container_name: nginx-demo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app1
      - app2

  app1:
    image: app1
    container_name: app1
    build:
      context: ./app1
    expose:
      - "5001"
    #restart: on-failure

  app2:
    image: app2
    container_name: app2
    build:
      context: ./app2
    expose:
      - "5002"
    #restart: on-failure

